#--------------------Water-phantom---------------------#
/gate/world/daughters/name waterPhantom
/gate/world/daughters/insert            box
/gate/waterPhantom/geometry/setXLength 200.0 mm
/gate/waterPhantom/geometry/setZLength 200.0 mm
/gate/waterPhantom/geometry/setYLength 200.0 mm
/gate/waterPhantom/placement/setTranslation 0 0 0 mm
/gate/waterPhantom/setMaterial Water
/gate/waterPhantom/vis/setVisible 1
/gate/waterPhantom/vis/setColor blue
